export const TOKEN = '_10darts_token';
export const DEVICE = '_10darts_device';
export const PERSONA = '_10darts_persona';
export const PUBLIC_KEY = '_10darts_publicKey';
export const LAST_ACCESS = '_10darts_last_access';
export const CREATE_USER_EVENT = '10DARTS_CREATE_USER';
export const SERVER_URL = process.env.SERVER_URL || 'http:localhost:8888';
export const URL_API = `${SERVER_URL}/api/v1`;
export const URL_API_V1 = `${SERVER_URL}/api/v1`;
